name: Linux Build

on:
  push:
    branches: [exodus, cmake]
  pull_request:

jobs:
  build:
    name: Debug
    runs-on: ubuntu-latest
    steps:
        #Basic stuff
      - uses: actions/checkout@v2
      - name: update repos
        run: sudo apt-get update
      - name: install libs
        run: sudo apt-get install cmake meson libsdl2-dev libsdl2-net-dev libogg-dev libvorbis-dev libboost-dev libvulkan-dev glslang-tools
        
        #Main build
      - name: create build dir
        run: mkdir build
      - name: configure
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug
        working-directory: build
      - name: build
        run: ninja
        working-directory: build
