name: Windows MSYS 64bit Build

on:
  push:
  pull_request:

jobs:
  debug:
    name: Debug
    runs-on: windows-latest
    steps:
      - uses: stalkerg/setup-msys2@v2
        with:
          msystem: MINGW64
      - name: install libs
        run: msys2do pacman --noconfirm -S
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-lld
          mingw-w64-x86_64-libbacktrace
          mingw-w64-x86_64-nasm
          mingw-w64-x86_64-yasm
      - name: ffmpeg -- download
        run: git clone --depth 1 --branch n4.2.2 https://git.ffmpeg.org/ffmpeg.git ffmpeg
      - name: ffmpeg -- configure
        run: msys2do ./configure --enable-shared --prefix=/mingw64
          --disable-everything
          --enable-swscale
          --enable-zlib
          --enable-demuxer=avi,rawvideo
          --enable-decoder=png,bink,rawvideo
          --enable-parser=png
          --enable-protocol=file
          --disable-d3d11va
          --disable-dxva2
          --disable-doc --disable-ffplay --disable-ffprobe --disable-ffmpeg
          --disable-static --disable-bzlib --disable-libopenjpeg --disable-iconv
        working-directory: ffmpeg
      - name: ffmpeg -- build and install
        run: |
          msys2do mingw32-make -j4
          msys2do mingw32-make install
        working-directory: ffmpeg
      - uses: actions/checkout@v2
      - name: perimeter -- create build dir
        run: msys2do mkdir build
      - name: perimeter -- configure
        run: msys2do cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Debug -DOPTION_PROCESS_SCRIPTS=ON
        working-directory: build
      - name: perimeter -- make
        run: msys2do ninja
        working-directory: build
      - name: perimeter -- prepare release folder
        run: |
          msys2do mkdir -p perimeter/bin
          msys2do cp /mingw64/bin/SDL2.dll perimeter/bin/
          msys2do cp /mingw64/bin/libgcc_*.dll perimeter/bin/
          msys2do cp /mingw64/bin/libstdc++-6.dll perimeter/bin/
          msys2do cp /mingw64/bin/libwinpthread-1.dll perimeter/bin/
          msys2do cp /mingw64/bin/libogg-0.dll perimeter/bin/
          msys2do cp /mingw64/bin/libvorbis-0.dll perimeter/bin/
          msys2do cp /mingw64/bin/libvorbisfile-3.dll perimeter/bin/
          msys2do cp /mingw64/bin/libbacktrace-0.dll perimeter/bin/
          msys2do cp /mingw64/bin/avcodec-58.dll perimeter/bin/
          msys2do cp /mingw64/bin/avformat-58.dll perimeter/bin/
          msys2do cp /mingw64/bin/avutil-56.dll perimeter/bin/
          msys2do cp /mingw64/bin/zlib1.dll perimeter/bin/
          cp build/Source/perimeter.exe perimeter/bin/
      - uses: actions/upload-artifact@v1
        with:
          name: Perimeter-Windows-MSYS-64-Debug
          path: perimeter
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - uses: stalkerg/setup-msys2@v2
        with:
          msystem: MINGW64
      - name: install libs
        run: msys2do pacman --noconfirm -S
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-lld
          mingw-w64-x86_64-libbacktrace
          mingw-w64-x86_64-nasm
          mingw-w64-x86_64-yasm
      - name: ffmpeg -- download
        run: git clone --depth 1 --branch n4.2.2 https://git.ffmpeg.org/ffmpeg.git ffmpeg
      - name: ffmpeg -- configure
        run: msys2do ./configure --enable-shared --prefix=/mingw64
          --disable-everything
          --enable-swscale
          --enable-zlib
          --enable-demuxer=avi,rawvideo
          --enable-decoder=png,bink,rawvideo
          --enable-parser=png
          --enable-protocol=file
          --disable-d3d11va
          --disable-dxva2
          --disable-doc --disable-ffplay --disable-ffprobe --disable-ffmpeg
          --disable-static --disable-bzlib --disable-libopenjpeg --disable-iconv
        working-directory: ffmpeg
      - name: ffmpeg -- build and install
        run: |
          msys2do mingw32-make -j4
          msys2do mingw32-make install
        working-directory: ffmpeg
      - uses: actions/checkout@v2
      - name: perimeter -- create build dir
        run: msys2do mkdir build
      - name: perimeter -- configure
        run: msys2do cmake -G Ninja ..
        working-directory: build
      - name: perimeter -- make
        run: msys2do ninja
        working-directory: build
      - name: perimeter -- prepare release folder
        run: |
          msys2do mkdir -p perimeter/bin
          msys2do cp /mingw64/bin/SDL2.dll perimeter/bin/
          msys2do cp /mingw64/bin/libgcc_*.dll perimeter/bin/
          msys2do cp /mingw64/bin/libstdc++-6.dll perimeter/bin/
          msys2do cp /mingw64/bin/libwinpthread-1.dll perimeter/bin/
          msys2do cp /mingw64/bin/libogg-0.dll perimeter/bin/
          msys2do cp /mingw64/bin/libvorbis-0.dll perimeter/bin/
          msys2do cp /mingw64/bin/libvorbisfile-3.dll perimeter/bin/
          msys2do cp /mingw64/bin/libbacktrace-0.dll perimeter/bin/
          msys2do cp /mingw64/bin/avcodec-58.dll perimeter/bin/
          msys2do cp /mingw64/bin/avformat-58.dll perimeter/bin/
          msys2do cp /mingw64/bin/avutil-56.dll perimeter/bin/
          msys2do cp /mingw64/bin/zlib1.dll perimeter/bin/
          cp build/Source/perimeter.exe perimeter/bin/
          msys2do strip perimeter/bin/perimeter.exe
      - uses: actions/upload-artifact@v1
        with:
          name: Perimeter-Windows-MSYS-64
          path: perimeter
